FROM openjdk:8-jdk

# 设置工作目录
WORKDIR /app

# 复制项目的所有文件
COPY . /app

# 确保mvnw具有可执行权限
RUN chmod +x /app/mvnw

# 设置环境变量
ENV MAVEN_HOME=/app

# 进入特定的微服务目录并构建项目
WORKDIR /app/IntelliEdu-application-service
RUN $MAVEN_HOME/mvnw clean install
