spring:
  application:
    name: IntelliEdu-api
  session:
    store-type: redis
    timeout: 2592000 # 30 days expiration
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR}
feign:
  client:
    config:
      default:
        connectTimeout: 5000  # milliseconds
        readTimeout: 10000    # milliseconds
