server:
  port: 8085
spring:
  application:
    name: IntelliEdu-gateway
  main:
    web-application-type: reactive
  cloud:
#    gateway:
#      routes:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: openapi3
      excluded-services:
        - IntelliEdu-gateway