server:
  port: 8085
spring:
  application:
    name: IntelliEdu-gateway
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR}
    gateway:
      routes:
        - id: IntelliEdu-user-service
          uri: lb://IntelliEdu-user-service
          predicates:
            - Path=/api/user/**
        - id: IntelliEdu-application-service
          uri: lb://IntelliEdu-application-service
          predicates:
            - Path=/api/application/**
        - id: IntelliEdu-scoring-service
          uri: lb://IntelliEdu-scoring-service
          predicates:
            - Path=/api/scoring/**
        - id: IntelliEdu-answer-record-service
          uri: lb://IntelliEdu-answer-record-service
          predicates:
            - Path=/api/answer-record/**
knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: openapi3
      excluded-services:
        - IntelliEdu-gateway