apiVersion: v1
kind: Service
metadata:
  name: intelliedu-gateway
  namespace: intelliedu
spec:
  type: ClusterIP # 配置了 ingress nginx，nginx 作为 loadBalancer，gateway 供 nginx 内部访问即可
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8085
  selector:
    app: intelliedu-gateway
