apiVersion: v1
kind: Service
metadata:
  name: intelliedu-gateway
  namespace: intelliedu
spec:
  selector:
    app: intelliedu-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  # 选择一个未使用的端口
  type: NodePort
