apiVersion: v1
kind: Service
metadata:
  name: intelliedu-user-service
  namespace: intelliedu
spec:
  selector:
    app: intelliedu-user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30002  # 选择一个未使用的端口
  type: NodePort
