apiVersion: v1
kind: Service
metadata:
  name: intelliedu-gateway
  namespace: intelliedu
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: intelliedu-gateway
