apiVersion: v1
kind: Service
metadata:
  name: intelliedu-scoring-service
  namespace: intelliedu
spec:
  selector:
    app: intelliedu-scoring-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30005  # 选择一个未使用的端口
  type: NodePort