apiVersion: v1
kind: Service
metadata:
  name: intelliedu-gateway
  namespace: intelliedu
spec:
  selector:
    app: intelliedu-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
