apiVersion: v1
kind: Service
metadata:
  name: intelliedu-answer-record-service
  namespace: intelliedu
spec:
  selector:
    app: intelliedu-answer-record-service
  ports:
    - protocol: TCP
      port: 80 # 集群内部使用的端口
      targetPort: 8084 # 应用实际监听的端口
      nodePort: 30003  # 外部访问的高位端口（确保未被占用）
  type: NodePort
