apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
      - name: nacos
        image: nacos/nacos-server:v2.2.0-slim
        ports:
        - containerPort: 8848
        env:
        - name: MODE
          value: "standalone"
