apiVersion: v1
kind: Service
metadata:
  name: nacos
spec:
  selector:
    app: nacos
  ports:
    - name: http
      protocol: TCP
      port: 8848
      targetPort: 8848
    - name: grpc
      protocol: TCP
      port: 9848
      targetPort: 9848
  type: ClusterIP
