apiVersion: v1
kind: Service
metadata:
  name: nacos-service
spec:
  selector:
    app: nacos
  ports:
    - protocol: TCP
      port: 8848
      targetPort: 8848
    - protocol: TCP
      port: 9848
      targetPort: 9848
  type: ClusterIP
