name: Deploy to DigitalOcean Kubernetes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pull Docker images
      run: |
        docker pull austinpang/intelliedu-gateway:latest
        docker pull austinpang/intelliedu-user-service:latest
        docker pull austinpang/intelliedu-application-service:latest
        docker pull austinpang/intelliedu-scoring-service:latest
        docker pull austinpang/intelliedu-answer-record-service:latest

    - name: Set up DigitalOcean Kubernetes context
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Kubernetes context
      run: doctl kubernetes cluster kubeconfig save k8s-intelliedu-nus

    - name: Apply intelliedu-gateway deployment
      run: kubectl apply -f k8s/intelliedu-gateway-deployment.yaml --namespace=intelliedu

    - name: Deploy intelliedu-gateway to Kubernetes
      run: |
        kubectl set image deployment/intelliedu-gateway intelliedu-gateway=austinpang/intelliedu-gateway:latest --namespace=intelliedu
        kubectl apply -f k8s/intelliedu-gateway-service.yaml --namespace=intelliedu

    - name: Apply intelliedu-user-service deployment
      run: kubectl apply -f k8s/intelliedu-user-service-deployment.yaml --namespace=intelliedu

    - name: Deploy intelliedu-user-service to Kubernetes
      run: |
        kubectl set image deployment/intelliedu-user-service intelliedu-user-service=austinpang/intelliedu-user-service:latest --namespace=intelliedu
        kubectl apply -f k8s/intelliedu-user-service-service.yaml --namespace=intelliedu

    - name: Apply intelliedu-application-service deployment
      run: kubectl apply -f k8s/intelliedu-application-service-deployment.yaml --namespace=intelliedu

    - name: Deploy intelliedu-application-service to Kubernetes
      run: |
        kubectl set image deployment/intelliedu-application-service intelliedu-application-service=austinpang/intelliedu-application-service:latest --namespace=intelliedu
        kubectl apply -f k8s/intelliedu-application-service-service.yaml --namespace=intelliedu

    - name: Apply intelliedu-scoring-service deployment
      run: kubectl apply -f k8s/intelliedu-scoring-service-deployment.yaml --namespace=intelliedu

    - name: Deploy intelliedu-scoring-service to Kubernetes
      run: |
        kubectl set image deployment/intelliedu-scoring-service intelliedu-scoring-service=austinpang/intelliedu-scoring-service:latest --namespace=intelliedu
        kubectl apply -f k8s/intelliedu-scoring-service-service.yaml --namespace=intelliedu

    - name: Apply intelliedu-answer-record-service deployment
      run: kubectl apply -f k8s/intelliedu-answer-record-service-deployment.yaml --namespace=intelliedu

    - name: Deploy intelliedu-answer-record-service to Kubernetes
      run: |
        kubectl set image deployment/intelliedu-answer-record-service intelliedu-answer-record-service=austinpang/intelliedu-answer-record-service:latest --namespace=intelliedu
        kubectl apply -f k8s/intelliedu-answer-record-service-service.yaml --namespace=intelliedu
