name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Initialize Maven Wrapper
      run: |
        mvn -N io.takari:maven:wrapper

    - name: Set execute permission for mvnw
      run: chmod +x ./mvnw

    - name: Save workspace
      uses: actions/upload-artifact@v2
      with:
        name: workspace
        path: .

  build-dependencies:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        service: [common, model]

    steps:
    - name: Download workspace
      uses: actions/download-artifact@v2
      with:
        name: workspace

    - name: Build IntelliEdu-${{ matrix.service }}
      run: |
        ./mvnw clean install -f IntelliEdu-${{ matrix.service }}/pom.xml

  build-services:
    runs-on: ubuntu-latest
    needs: [setup, build-dependencies]
    strategy:
      matrix:
        service: [api, gateway, user-service, application-service, scoring-service, answer-record-service]

    steps:
    - name: Download workspace
      uses: actions/download-artifact@v2
      with:
        name: workspace

    - name: Build and push IntelliEdu-${{ matrix.service }}
      uses: docker/build-push-action@v2
      with:
        context: .
        file: IntelliEdu-${{ matrix.service }}/Dockerfile.jdk8
        push: true
        tags: austinpang/intelliedu-${{ matrix.service }}:latest

  sonar:
    runs-on: ubuntu-latest
    needs: [setup, build-dependencies, build-services]
    strategy:
      matrix:
        service: [common, model, api, gateway, user-service, application-service, scoring-service, answer-record-service]

    steps:
    - name: Download workspace
      uses: actions/download-artifact@v2
      with:
        name: workspace

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: SonarQube Scan for IntelliEdu-${{ matrix.service }}
      run: |
        ./mvnw sonar:sonar \
          -Dsonar.projectKey=intelliedu-${{ matrix.service }} \
          -Dsonar.host.url=http://159.223.35.44:8888 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -f IntelliEdu-${{ matrix.service }}/pom.xml
