name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set execute permission for mvnw
      run: chmod +x ./mvnw

    - name: Build and push IntelliEdu-common
      uses: docker/build-push-action@v2
      with:
        context: .
        file: IntelliEdu-common/Dockerfile.jdk8
        push: true
        tags: austinpang/intelliedu-common:latest

    - name: Build and push IntelliEdu-model
      uses: docker/build-push-action@v2
      with:
        context: .
        file: IntelliEdu-model/Dockerfile.jdk8
        push: true
        tags: austinpang/intelliedu-model:latest

    - name: Build and push IntelliEdu-api
      uses: docker/build-push-action@v2
      with:
        context: .
        file: IntelliEdu-api/Dockerfile.jdk8
        push: true
        tags: austinpang/intelliedu-api:latest

    - name: Build and push IntelliEdu-gateway
      uses: docker/build-push-action@v2
      with:
        context: .
        file: IntelliEdu-gateway/Dockerfile.jdk8
        push: true
        tags: austinpang/intelliedu-gateway:latest

    - name: Build and push IntelliEdu-user-service
      uses: docker/build-push-action@v2
      with:
        context: .
        file: IntelliEdu-user-service/Dockerfile.jdk8
        push: true
        tags: austinpang/intelliedu-user-service:latest

    - name: Build and push IntelliEdu-application-service
      uses: docker/build-push-action@v2
      with:
        context: .
        file: IntelliEdu-application-service/Dockerfile.jdk8
        push: true
        tags: austinpang/intelliedu-application-service:latest

    - name: Build and push IntelliEdu-scoring-service
      uses: docker/build-push-action@v2
      with:
        context: .
        file: IntelliEdu-scoring-service/Dockerfile.jdk8
        push: true
        tags: austinpang/intelliedu-scoring-service:latest

    - name: Build and push IntelliEdu-answer-record-service
      uses: docker/build-push-action@v2
      with:
        context: .
        file: IntelliEdu-answer-record-service/Dockerfile.jdk8
        push: true
        tags: austinpang/intelliedu-answer-record-service:latest
