name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: 
          - { name: IntelliEdu-common, lower: intelliedu-common }
          - { name: IntelliEdu-model, lower: intelliedu-model }
          - { name: IntelliEdu-api, lower: intelliedu-api }
          - { name: IntelliEdu-gateway, lower: intelliedu-gateway }
          - { name: IntelliEdu-user-service, lower: intelliedu-user-service }
          - { name: IntelliEdu-application-service, lower: intelliedu-application-service }
          - { name: IntelliEdu-scoring-service, lower: intelliedu-scoring-service }
          - { name: IntelliEdu-answer-record-service, lower: intelliedu-answer-record-service }

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./${{ matrix.service.name }}
        file: Dockerfile.jdk8
        push: true
        tags: austinpang/${{ matrix.service.lower }}:latest
