name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Initialize Maven Wrapper
      run: |
        mvn -N io.takari:maven:wrapper

    - name: Set execute permission for mvnw
      run: chmod +x ./mvnw

    - name: Build and push IntelliEdu-common
      uses: docker/build-push-action@v2
      with:
        context: .
        file: IntelliEdu-common/Dockerfile.jdk8
        push: true
        tags: austinpang/intelliedu-common:latest

    - name: Build and push IntelliEdu-model
      uses: docker/build-push-action@v2
      with:
        context: .
        file: IntelliEdu-model/Dockerfile.jdk8
        push: true
        tags: austinpang/intelliedu-model:latest

    - name: Build and push IntelliEdu-api
      uses: docker/build-push-action@v2
      with:
        context: .
        file: IntelliEdu-api/Dockerfile.jdk8
        push: true
        tags: austinpang/intelliedu-api:latest

    - name: Build and push IntelliEdu-gateway
      uses: docker/build-push-action@v2
      with:
        context: .
        file: IntelliEdu-gateway/Dockerfile.jdk8
        push: true
        tags: austinpang/intelliedu-gateway:latest

    - name: Build and push IntelliEdu-user-service
      uses: docker/build-push-action@v2
      with:
        context: .
        file: IntelliEdu-user-service/Dockerfile.jdk8
        push: true
        tags: austinpang/intelliedu-user-service:latest

    - name: Build and push IntelliEdu-application-service
      uses: docker/build-push-action@v2
      with:
        context: .
        file: IntelliEdu-application-service/Dockerfile.jdk8
        push: true
        tags: austinpang/intelliedu-application-service:latest

    - name: Build and push IntelliEdu-scoring-service
      uses: docker/build-push-action@v2
      with:
        context: .
        file: IntelliEdu-scoring-service/Dockerfile.jdk8
        push: true
        tags: austinpang/intelliedu-scoring-service:latest

    - name: Build and push IntelliEdu-answer-record-service
      uses: docker/build-push-action@v2
      with:
        context: .
        file: IntelliEdu-answer-record-service/Dockerfile.jdk8
        push: true
        tags: austinpang/intelliedu-answer-record-service:latest

  sonar:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Initialize Maven Wrapper
      run: |
        mvn -N io.takari:maven:wrapper

    - name: Set execute permission for mvnw
      run: chmod +x ./mvnw

    - name: SonarQube Scan for IntelliEdu-common
      run: |
        ./mvnw sonar:sonar \
          -Dsonar.projectKey=intelliedu-common \
          -Dsonar.host.url=http://159.223.35.44:8888 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -f IntelliEdu-common/pom.xml

    - name: SonarQube Scan for IntelliEdu-model
      run: |
        ./mvnw sonar:sonar \
          -Dsonar.projectKey=intelliedu-model \
          -Dsonar.host.url=http://159.223.35.44:8888 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -f IntelliEdu-model/pom.xml

    - name: SonarQube Scan for IntelliEdu-api
      run: |
        ./mvnw sonar:sonar \
          -Dsonar.projectKey=intelliedu-api \
          -Dsonar.host.url=http://159.223.35.44:8888 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -f IntelliEdu-api/pom.xml

    - name: SonarQube Scan for IntelliEdu-gateway
      run: |
        ./mvnw sonar:sonar \
          -Dsonar.projectKey=intelliedu-gateway \
          -Dsonar.host.url=http://159.223.35.44:8888 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -f IntelliEdu-gateway/pom.xml

    - name: SonarQube Scan for IntelliEdu-user-service
      run: |
        ./mvnw sonar:sonar \
          -Dsonar.projectKey=intelliedu-user-service \
          -Dsonar.host.url=http://159.223.35.44:8888 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -f IntelliEdu-user-service/pom.xml

    - name: SonarQube Scan for IntelliEdu-application-service
      run: |
        ./mvnw sonar:sonar \
          -Dsonar.projectKey=intelliedu-application-service \
          -Dsonar.host.url=http://159.223.35.44:8888 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -f IntelliEdu-application-service/pom.xml

    - name: SonarQube Scan for IntelliEdu-scoring-service
      run: |
        ./mvnw sonar:sonar \
          -Dsonar.projectKey=intelliedu-scoring-service \
          -Dsonar.host.url=http://159.223.35.44:8888 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -f IntelliEdu-scoring-service/pom.xml

    - name: SonarQube Scan for IntelliEdu-answer-record-service
      run: |
        ./mvnw sonar:sonar \
          -Dsonar.projectKey=intelliedu-answer-record-service \
          -Dsonar.host.url=http://159.223.35.44:8888 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -f IntelliEdu-answer-record-service/pom.xml
