name: CI/CD Pipeline - SonarQube Analysis

on:
  push:
    branches:
      - master

jobs:
  sonar-common:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11 for SonarQube
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: SonarQube Scan for IntelliEdu-common
      run: |
        ./mvnw sonar:sonar -X \
          -Dsonar.projectKey=intelliedu-common \
          -Dsonar.host.url=http://159.223.35.44:8888 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.java.binaries=$(pwd)/IntelliEdu-common/target/classes \
          -f IntelliEdu-common/pom.xml

  sonar-model-api:
    runs-on: ubuntu-latest
    needs: sonar-common
    strategy:
      matrix:
        service: [model, api]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11 for SonarQube
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: SonarQube Scan for IntelliEdu-${{ matrix.service }}
      run: |
        ./mvnw sonar:sonar -X \
          -Dsonar.projectKey=intelliedu-${{ matrix.service }} \
          -Dsonar.host.url=http://159.223.35.44:8888 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.java.binaries=$(pwd)/IntelliEdu-${{ matrix.service }}/target/classes \
          -f IntelliEdu-${{ matrix.service }}/pom.xml

  sonar-other-services:
    runs-on: ubuntu-latest
    needs: sonar-model-api
    strategy:
      matrix:
        service: [gateway, user-service, application-service, scoring-service, answer-record-service]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11 for SonarQube
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: SonarQube Scan for IntelliEdu-${{ matrix.service }}
      run: |
        ./mvnw clean compile sonar:sonar -X \
          -Dsonar.projectKey=intelliedu-${{ matrix.service }} \
          -Dsonar.host.url=http://159.223.35.44:8888 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.java.binaries=$(pwd)/IntelliEdu-${{ matrix.service }}/target/classes \
          -f IntelliEdu-${{ matrix.service }}/pom.xml
