name: CI/CD Pipeline - Test

on:
  push:
    branches:
      - master

jobs:
  test-common:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 8 for build
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Initialize Maven Wrapper
      run: |
        mvn -N io.takari:maven:wrapper

    - name: Set execute permission for mvnw
      run: chmod +x ./mvnw

    - name: Build and test all modules
      run: ./mvnw clean install test

  test-model-api:
    runs-on: ubuntu-latest
    needs: test-common
    strategy:
      matrix:
        service: [model, api]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 8 for build
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '8'
      
    - name: Initialize Maven Wrapper
      run: |
          mvn -N io.takari:maven:wrapper

    - name: Set execute permission for mvnw
      run: chmod +x ./mvnw

    - name: Build and test all modules
      run: ./mvnw clean install test

  test-other-services:
    runs-on: ubuntu-latest
    needs: test-model-api
    strategy:
      matrix:
        service: [gateway, user-service, application-service, scoring-service, answer-record-service]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 8 for build
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Set execute permission for mvnw
      run: chmod +x ./mvnw

    - name: Build and test all modules
      run: ./mvnw clean install test -X